[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "prometheus-fastapi-instrumentator"
version = "7.0.0"
description = "Instrument your FastAPI with Prometheus metrics."
authors = ["Tim Schwenke <tim@trallnag.com>"]
license = "ISC"
readme = "README.md"
repository = "https://github.com/trallnag/prometheus-fastapi-instrumentator"
keywords = ["prometheus", "instrumentation", "fastapi", "exporter", "metrics"]

[tool.poetry.dependencies]
python = ">= 3.8.1, < 4.0.0"
starlette  = ">= 0.30.0, < 1.0.0"
prometheus-client = ">= 0.8.0, < 1.0.0"

[tool.poetry.group.dev.dependencies]
httpx = "^0.23.3"
black = "^24.2.0"
flake8 = "^7.0.0"
requests = "^2.31.0"
pytest = "^8.1.1"
pytest-cov = "^4.1.0"
rope = "^1.12.0"
isort = "^5.13.2"
mypy = "^1.9.0"
devtools = "^0.10.0"
asgiref = "^3.7.2"
uvicorn = ">=0.28.0"
gunicorn = ">=21.2,<23.0"
pytest-asyncio = ">=0.23.5.post1"
fastapi = "^0.110.0"

[tool.black]
line-length = 90

[tool.isort]
profile = "black"

[tool.mypy]
allow_redefinition = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true

[tool.pytest.ini_options]
norecursedirs = "tests/helpers"
markers = ["slow: mark test as slow."]
asyncio_mode = "auto"
